# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tangara Pipeline

on:
  schedule:
    - cron: '0 * * * *'
#  push:
#    branches:
#      - "feature/tangara-stations"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --cov-fail-under=90
    - name: Tangara Pipeline
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Run tangara-pipeline
        ./run.sh
        # Check any change
        echo $(git status --porcelain)
        if [[ $(git status --porcelain) ]]; then
          echo "Tangara Pipeline Executed"
          echo ""
          git config --global user.email 'sebaxtianrioss@gmail.com'
          git config --global user.name 'Sebastian Rios Sabogal'
          git add .
          git commit -m "Tangara Pipeline Executed at $(TZ='America/Bogota' date '+%Y-%m-%dT%H:%M:%S') America/Bogota"
          # git push origin feature/tangara-stations
          git push origin master
        else
          echo "Not Changes related to Tangara Pipeline"
        fi
        echo ""
